name: PR update

on:
  push:
    branches: 
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Update All Pull Requests
        uses: juliangruber/update-pull-request-branch-action@v1
        with:
          waitForPullRequestUpdated: false
          github_token: ${{ secrets.GITHUB_TOKEN }}

